### ISSUE TITLE
Quelques problèmes

### ISSUE THREAD

**Issue by yomli** [OneCoderToRuleThemAll/cv.example#1]
J'ai noté quelques soucis avec cette version. J'imagine que tu bosses toi-même sur l'amélioration, mais voici ce que je note :

#### CSS
Le fichier CSS se nomme CSS2.css alors qu'il est appelé par CSS.css dans le HTML (ligne 7) :
``` HTML
<link href="CSS.css" rel="stylesheet" type="text/css" />
```
Fix possible : renommer le fichier CSS2 en CSS ou bien l'appeler par CSS2 dans le `head`.

#### Fin de paragraphe

Ligne 19 du HTML, la balise de fermeture est mise alors qu'il n'y a pas de balise d'ouverture du paragraphe. Je conseille d'enlever la fermeture après _Your full name_ (ligne 14) :
``` HTML
    <p><strong>Your full name</strong><br>
    Your<br>
    Adress<br>
    <strong>Tel. :</strong> your phone number<br>
    <strong>mob. :</strong> your mobile phone number<br>
    <strong>@ :</strong> your e-mail</p>
```

#### L'underline et l'emphase

Même si ce n'est pas vraiment une erreur, tu peux éviter d'utiliser les balises `<u>`. 

D'une, parce que typographiquement parlant, le souligné est à réserver aux [liens hypertexte et aux machines à écrire](http://practicaltypography.com/underlining.html) (c'est une hérésie typographique que d'utiliser une emphase et un souligné, vu que le souligné a été inventé pour les machines à écrire justement parce qu'elles ne pouvaient pas toutes faire des italiques ou des gras).

De deux, parce qu'il est bien plus élégant de faire ça en CSS plutôt qu'en HTML. Ici, toutes tes `<em>` sont utilisées avec `<u>`, tu peux donc très bien ajouter une règle CSS :
``` CSS
em {
    /* On applique le souligné */
    text-decoration: underline;
   /* Et on explique que c'est en italique, <em> étant une emphase, 
      elle n'est pas identique à <i> et peut être affiché différemment
      sur certains navigateurs. Je n'ai par contre pas d'exemple,
      hormis les lecteurs d'écran pour aveugles il me semble. */
   font-style: italic;
}
```
Et supprimer, du coup, toutes les balises `<u>`. Dans le cas où tu aurais plusieurs `<em>` et que tu ne voudrais souligner que celles dans les listes :
``` CSS
ul li em {
	text-decoration: underline;
	font-style: italic;
}
```

#### Les images

L'image de GitHub manque de l'attribut `alt`. Cet attribut était obligatoire en xHTML, il ne l'est plus en HTML5, à mon grand désarroi. En effet, ici tu l'utilises pour un lien. Seulement, si l'image ne peut pas être chargée, le navigateur doit aller chercher le texte de l'attribut `alt` et l'afficher à la place. Donc à moins que tu n'ais un texte à côté de l'image, ou que l'image elle-même est optionnelle, il faut mettre un `alt` :
``` HTML
<a href="https://github.com/OneCoderToRuleThemAll" class="icon github"><img src="http://sciactive.com/pnotify/includes/github-icon.png" alt="GitHub"/></a>
```

Pour l'image de HTML5, il est plutôt conseillé de mettre tout ce qui est de l'alignement et de la taille dans le CSS :
``` CSS
/* On aligne à droite tout ce qui est
   contenu dans le footer */
footer {
	text-align: right;
}

/* On cible toutes les images du footer, ici il n'y en a qu'une
   donc ça va, mais on devra faire attention dans le cas où il
    y en a plusieurs */
footer img {
        /* Et, magie ! On a pas besoin de donner un width, il
           est calculé automatiquement par le navigateur ;) */
	height: 39px;
}
```

#### Les `<br>`

Tu utilises trop de `<br>` pour positionner tes éléments. Tout ce positionnement peut (et devrait) être fait en CSS. Exemple : tu as systématiquement un `<br>`  entre chaque liste. Non seulement le `<br>` n'a pas une taille consistante entre les navigateurs, mais il est assez mal vu en-dehors d'un paragraphe. Si on enlève les `<br>` entre chaque liste et qu'on cible en CSS :
``` CSS
ul {
        /* On ajoute une marge de 60px en haut et en bas, 
           mais on ne touche pas aux côtés */
	margin: 60px 0;
}
```
Et tu enveloppes le lien vers GitHub dans un paragraphe. Oui, on a le droit, et c'est même conseillé, de faire un paragraphe pour une seule phrase :)

#### Et le reste

Il y aurait encore pas mal de choses, mais c'est une question d'apprentissage et de style, donc je ne vais pas m'attarder dessus. Exemple : il n'y a pratiquement rien dans le `<head>`, ou bien un petit `padding` serait intéressant dans les `<div>`. Mais ça, je te laisse le découvrir au fur et à mesure.

Si tu veux gagner du temps, je peux te faire un `push` avec les modifications que j'ai apporté et que je viens de lister ici. Ça te permettra de ne pas avoir à tout intégrer par toi-même. En même temps, le faire à la main te permet aussi d'apprendre et de le mémoriser, donc j'hésite pas mal ;)

En tout cas c'est un bon début, à l'IUT j'ai vu des étudiants (et même des professeurs !) faire bien bien pire que ça, même après un semestre entier à travailler dessus. Donc tu es sur une bonne voie :+1:
